spring.application.name=payment-gateway
spring.profiles.active=${SPRING_PROFILES_ACTIVE:staging}

server.port=${SERVER_PORT:8090}
acquiring-bank.url=${ACQUIRING_BANK_URL:http://localhost:8080}

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.override-with-generic-response=false

management.endpoints.web.exposure.include=health,payments,metrics

server.error.include-message=always
server.error.include-stacktrace=always
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.com.checkout.payment.gateway=DEBUG
